### ISSUE TITLE
undefined reference to `__cudaPushCallConfiguration'

### ISSUE THREAD

**Issue by twaters** [cholla-hydro/cholla#17]
Just pulled latest changes and my previous compile settings no longer work.  I'm getting errors like this,
./src/VL_3D_cuda.o: In function `VL_Algorithm_3D_CUDA(double*, double*, int, int, int, int, int, int, int, double, double, double, double, double, double, double, int)':
tmpxft_00001c28_00000000-5_VL_3D_cuda.cudafe1.cpp:(.text+0x5ca): undefined reference to `__cudaPushCallConfiguration'

Tried with both cudatoolkit/9.0 and the latest, 10.1
Currently Loaded Modules:
  1) intel/18.0.5   2) openmpi/2.1.2   3) hdf5-parallel/1.8.16   4) java/1.8.0_45   5) cudatoolkit/10.1

**Comment by evaneschneider** [comment]
Are you on the master branch? I just checked that the master compiles on Summit using spectrumMPI and Cuda 10, but I've not seen that specific error before.

**Comment by twaters** [comment]
Yes I am.  I've tried cudatoolkit with intel-mpi also and get the same thing.

**Comment by twaters** [comment]
Have you compiled recently on the Princeton cluster?

**Comment by evaneschneider** [comment]
Yes, I just also successfully compiled the master branch on Princeton's cluster, using openmpi  and Cuda 10. One thing to check is to make sure you've got the correct Cuda architecture flag in your makefile - did you make any modifications relative to the makefile in the repo?

**Comment by evaneschneider** [comment]
Another note for reference is that Cholla does not use parallel-hdf5, but I don't see why that should give you a Cuda compile error. I assume you cleaned everything, as well...

**Comment by twaters** [comment]
Yes, I'm using my old Makefile that lives on my branch.  Just got it to work.  Relative to that Makefile, I had to change -arch=sm_20 to -arch=sm_70 and had to use cudatoolkit/9.0 instead of 10.0.  One fix for other codes seeing this error was not not use cudatoolkit/9.2 and above, so I guess that was the issue.

**Comment by evaneschneider** [comment]
Glad you got it working!

**Comment by twaters** [comment]
Yes, me too, thanks for the rapid response!

**Comment by henbucuoshanghai** [comment]
the same error   undefined reference to `__cudaPushCallConfiguration

it must be cuda9?
