### ISSUE TITLE
Spherical Collapse gravity test currently failing

### ISSUE THREAD

**Issue by bcaddy** [cholla-hydro/cholla#218]
The `tGRAVITYSYSTEMSphericalCollapse.CorrectInputExpectCorrectOutput` and `tPARTICLESSYSTEMSphericalCollapse.CorrectInputExpectCorrectOutput` system tests are currently failing on `dev`. Tested on C-3PO

**Comment by evaneschneider** [comment]
PR #223 should fix this.

**Comment by bcaddy** [comment]
It looks like PR #223 fixed the gravity test but not the particles test
