### ISSUE TITLE
Add wiki page on how to use static gravity

### ISSUE THREAD

**Issue by evaneschneider** [cholla-hydro/cholla#242]

**Comment by alwinm** [comment]
Stub for this is added here:

https://github.com/cholla-hydro/cholla/wiki/Gravity

**Comment by evaneschneider** [comment]
This is done. Ideally someday the documentation on how to use the analytic potentials with Paris will be described better / more fully, and there is no documentation for SOR, but since SOR is also not working with GRAVITY_GPU at present, I'm going to close this and make that it's own issue.
