### ISSUE TITLE
Regression test

### ISSUE THREAD

**Issue by dmcdougall** [cholla-hydro/cholla#25]
I'm opening this issue just to start the discussion on how to design and implement a simple regression test.  @evaneschneider mentioned once upon a time that the SOD test was reasonable.

How do you want this to look?  Is there a plot or a 'golden' result we can generate from the SOD test?  Do you want a `check` target in your `Makefile` so that you just have to type `make check` to run the test?  Is a makefile edit enough?  Should it be part of a more robust build system?

We don't have to do all of the above.  I'm just opening this issue to sort of start the discussion.

**Comment by evaneschneider** [comment]
These are all good questions, and I appreciate you opening the issue! Certainly the Sod test with default Makefile parameters is a good place to start, and I think we can use the code as it is now to generate targets to test against. Ideally we would have targets for all the various hydro combinations, but I'm not sure that's worth doing now. I like the idea of a check target, but I also think a "robust build system" sounds good. Let's discuss further.

**Comment by bcaddy** [comment]
I believe this is resolve by PR #94. Is that correct?

**Comment by evaneschneider** [comment]
Yes, and technically earlier versions of the regression test that were implemented, as well. We can close it!
