### ISSUE TITLE
buildAndRunTests broken on dev

### ISSUE THREAD

**Issue by evaneschneider** [cholla-hydro/cholla#280]
On the current version of dev, trying to execute buildAndRunTests fails. Reproduced by @helenarichie, perhaps a bug introduced by a recent PR touching paths in run_tests.sh?

Workflow to reproduce error:
checkout dev
source builds/run_tests.sh
buildAndRunTests -c gcc -t hydro

results in being bumped up to home directory with an error message, i.e.
make: *** No rule to make target 'clobber'.  Stop.

Running Setup...
fatal: not a git repository (or any of the parent directories): .git
bash: /builds/setup.c3po.gcc.sh: No such file or directory

Building Cholla...

make: *** No targets specified and no makefile found.  Stop.

**Comment by evaneschneider** [comment]
Running tests manually still works, i.e.
./bin/cholla.hydro.c3po.tests --cholla-root /home/evans/code/cholla --build-type hydro --machine c3po --gtest_filter=*tHYDRO*
is fine.

**Comment by alwinm** [comment]
As I understand it, this is because setupTests sets up the environment variable ```CHOLLA_ROOT``` but it is being used before the first invocation of setupTests in ```cd CHOLLA_ROOT``` which cds to nothing (aka home directory):

https://github.com/cholla-hydro/cholla/blame/dcec6fb9555890145cfa0017db8690ee2ad2a82e/builds/run_tests.sh#L252

**Comment by alwinm** [comment]
Until that's merged in you can run build and run tests by first manually doing this in the git repo

```export CHOLLA_ROOT="$(git rev-parse --show-toplevel)"```

**Comment by evaneschneider** [comment]
Fixed in PR #273.
