### ISSUE TITLE
Chemistry builds not compiling on dev

### ISSUE THREAD

**Issue by evaneschneider** [cholla-hydro/cholla#281]
PR #277 added two utility function calls to chemistry_functions.cpp, but the headers aren't included, so chemistry builds do not compile. Adding the headers fixes the issue (but I haven't done it yet on dev, only on RT, which will not get merged in soon).

**Comment by evaneschneider** [comment]
Yeah, I think that's a good idea. We should probably spend a hack session looking at what code is / isn't covered in the current build matrix, and try to add whatever builds we need to get as much of the code covered as possible.

**Comment by bcaddy** [comment]
Fixed in PR #283
