### ISSUE TITLE
`OUTPUT_ALWAYS` flag makes Cholla end at the wrong time

### ISSUE THREAD

**Issue by bcaddy** [cholla-hydro/cholla#301]
If the `OUTPUT_ALWAYS` macro is set then instead of Cholla ending at `tout` it outputs at the end of the first time step where `t > tout`. This is probably only an issue for debug builds and should be an easy fix, especially if `OUTPUT_ALWAYS` becomes a runtime argument instead of a compile time flag

**Comment by evaneschneider** [comment]
Fixed in PR #345
