### ISSUE TITLE
gravity isolated boundaries bug

### ISSUE THREAD

**Issue by ojwg** [cholla-hydro/cholla#47]
Bruno found a bug in 'src/gravity/gravity_boundaries.cpp' function 'Grid3D::Set_Potential_Boundaries_Isolated' https://github.com/cholla-hydro/cholla/blob/a23c042862d72fa6c8955e5305262c1a5599d29b/src/gravity/gravity_boundaries.cpp#L80  This issue raises awareness until the patch is submitted.

**Comment by evaneschneider** [comment]
Fixed with PR #49. Thanks!
