### ISSUE TITLE
GRAV_ISOLATED_BOUNDARY_Y identifier?

### ISSUE THREAD

**Issue by ojwg** [cholla-hydro/cholla#52]
https://github.com/cholla-hydro/cholla/blob/57bdb60856905607f74dd65be77b9c1b32df24c8/src/gravity/gravity_boundaries.cpp#L47

https://github.com/cholla-hydro/cholla/blob/57bdb60856905607f74dd65be77b9c1b32df24c8/src/gravity/gravity_boundaries.cpp#L115

**Comment by bvillasen** [comment]
fixed
