### ISSUE TITLE
CAAR branch memory leak

### ISSUE THREAD

**Issue by alwinm** [cholla-hydro/cholla#80]
I found a potential memory leak (no idea where it is). To reproduce, try the Rayleigh Taylor problem:
tests/2D/Rayleigh_Taylor.txt

set tout=40.0
outstep = 2.0

Split across 4 gpus (2x2) (single-GPU runs are fine) 

After sim time ~ 9.0, and 18000 time steps, the GPU runs out of memory 

I added these lines to the loop in main.cpp to see the memory grow:

```
    size_t free_t,total_t;
    cudaMemGetInfo(&free_t,&total_t);
    chprintf("GPU Memory Free: %zu Total: %zu Used: %zu \n",free_t,total_t,total_t-free_t);
```

Something strange is that it only seems to grow every few timesteps. So used memory is constant for 2-3 timesteps, then jumps up. Not sure if this is a feature of cudaMemGetInfo or a clue for where the leak might be. 

The memory usage is growing by 2097152=2**21 when it grows. Not sure what the significance of this is, either. 

The growth averaged over 18550 timesteps is 835751 bytes per timestep

The Rayleigh_Taylor domain size is nx=200 ny=400

**Comment by reubendb** [comment]
I can not reproduce this with my [CAAR branch](https://github.com/reubendb/cholla/commit/149604a33e87a2252e1d2c4e62181360c9db6bae ), which is basically the main CAAR branch minus [PR76](https://github.com/cholla-hydro/cholla/pull/76) but with [PR81](https://github.com/cholla-hydro/cholla/pull/81).

1. Could you confirm the CUDA version you use? 
2. Could you point me to a specific commit to reproduce?
3. I am sorry but I don't follow the comment with `CudaSafeCall()`. Why would you suspect anything with `CudaSafeCall()`, or `cudaMemCpy()` for that matter?

Here's output from Rayleigh Taylor from the first and next to last snapshot (I added the `cudaMemGetInfo()` call inside the output branch) with 4 MPIs (4 GPUs):
```
Saving Snapshot: 1 
GPU Memory Free: 15542.910976 MB Total: 16945.512448 MB Used: 1402.601472 MB 
n_step: 4086   sim time:  2.0004871   sim timestep: 4.8713e-04  timestep time =     0.503 ms   total time =    2.7173 s
... 

Saving Snapshot: 24 
GPU Memory Free: 15542.910976 MB Total: 16945.512448 MB Used: 1402.601472 MB 
n_step: 98479   sim time: 48.0004886   sim timestep: 4.8856e-04  timestep time =     0.587 ms   total time =   47.4352 s
```

And output from 3D Sod with 512**3 cells, 8 MPIs (8 GPUs):
```
Saving Snapshot: 1 
GPU Memory Free: 5640.159232 MB Total: 16945.512448 MB Used: 11305.353216 MB 
n_step: 404   sim time:  0.1002472   sim timestep: 2.4718e-04  timestep time =   122.545 ms   total time =   57.1675 s
...
Saving Snapshot: 100 
GPU Memory Free: 5640.159232 MB Total: 16945.512448 MB Used: 11305.353216 MB 
n_step: 17319   sim time: 10.0007398   sim timestep: 7.3979e-04  timestep time =   117.475 ms   total time = 2379.9040 s
```

**Comment by alwinm** [comment]
I had run into the problem with the following older commits:
94fdc498101d98279008e1e6a7ba0ae030da23cd
ba9683358f81f5460c054d0d812163c64a8d3643

But much to my confusion I cannot reproduce the error anymore, with the older commits or any of the newer ones. 
It's possible that something was just subtly wrong in my environment. Since I did not find the leak using HIP I don't think it can be a problem with the cholla codebase.
