### ISSUE TITLE
Slightly different results in serial vs. MPI runs

### ISSUE THREAD

**Issue by bcaddy** [cholla-hydro/cholla#92]
While implementing some Sod system test I found that running Cholla with 4 MPI ranks leads to slightly different results than running with 1 or 2 and the difference is resolution dependent. 

| Resolution | Approx. Absolute Error |
| ---------- |------------------------|
| 4^3        | ~10^-2                 |
| 16^3       | ~10^-8                 |
| 32^3       | ~10^-10                |
| 64^3       | <10^-14                |

**Comment by alwinm** [comment]
I think we can close this issue. I don't find differences between serial/MPI anymore. Re-open if divergences are rediscovered.
