### ISSUE TITLE
M_sun (low priority)

### ISSUE THREAD

**Issue by alwinm** [cholla-hydro/cholla#97]
In global/global.h:

MSUN_CGS is set to 1.988**47**e33. This def is only used in cooling_grackle to convert Cosmo.rho_0_gas to CGS. 
MASS_UNIT is set to 1.988**55**e33 with the comment // 1 solar mass in grams. 

It seems to me that perhaps the two should be made consistent.

**Comment by alwinm** [comment]
I believe this is fixed thanks to Bob!

**Comment by bcaddy** [comment]
I think it is fixed but @evaneschneider made the change while going through PR #136

**Comment by alwinm** [comment]
Oops, I hadn't looked carefully enough through the PR. Thank you for the correction!
